name: "Auto Code Generation with Claude on Issue"

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
        type: string

# Add permissions block
permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  codegen:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Configure Git identity
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 3. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      # 4. Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install anthropic requests

      # 5. Create a new branch named "claude-pr/issue-<number>" from origin/main
      - name: Create Issue Branch
        id: create_branch
        run: |
          ISSUE_NUMBER=${{ inputs.issue_number }}
          BRANCH_NAME="claude-pr/issue-${ISSUE_NUMBER}"
          
          # Create new branch from origin/main without checking it out
          git fetch origin main
          git branch "$BRANCH_NAME" origin/main
          git checkout "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT

      # 6. Generate code using Claude via Python script
      - name: Generate code with Claude
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # Create output directories
          mkdir -p .github/generated/{workflows,scripts}
          
          # Run generate_code.py to get Claude's response
          python .github/scripts/generate_code.py
          
          # Extract and save code blocks from Claude's response
          if [ -f ".github/generated/claude_conversation.json" ]; then
            # Get code blocks from conversation
            code_blocks=$(jq -r '.claude_response' .github/generated/claude_conversation.json)
            
            # Save workflow file
            if echo "$code_blocks" | grep -q "yaml:.github/workflows/combined_ct_images_to_text.yml"; then
              echo "$code_blocks" | sed -n '/```yaml:.github\/workflows\/combined_ct_images_to_text.yml/,/```/p' | sed '1d;$d' > .github/generated/workflows/combined_ct_images_to_text.yml
              echo "Saved workflow file"
            fi
            
            # Save Python file
            if echo "$code_blocks" | grep -q "python:.github/scripts/url_screenshot_check.py"; then
              echo "$code_blocks" | sed -n '/```python:.github\/scripts\/url_screenshot_check.py/,/```/p' | sed '1d;$d' > .github/generated/scripts/url_screenshot_check.py
              echo "Saved Python file"
            fi
          else
            echo "Error: Claude conversation file not found"
            exit 1
          fi
          
          # Debug generated files
          echo "Generated files:"
          ls -R .github/generated/
          
          # Commit the changes
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .github/generated/
          git commit -m "Generated code files for issue #${{ github.event.inputs.issue_number }}"
          git push origin HEAD:${{ steps.create_branch.outputs.BRANCH_NAME }}

      # After generating code but before creating PR
      - name: Save workflow data
        run: |
          if [ -f ".github/generated/metadata.json" ]; then
            cp .github/generated/metadata.json ./workflow-data.json
          else
            echo "{\"issue_number\": \"${{ inputs.issue_number }}\"}" > workflow-data.json
          fi

      - name: Upload workflow data
        uses: actions/upload-artifact@v3
        with:
          name: workflow-data
          path: workflow-data.json

      # Save artifacts
      - name: Save Claude conversation
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: claude-conversation
          path: |
            .github/generated/claude_conversation.json
            .github/generated/claude_conversation_error.json
          if-no-files-found: warn
