name: "Auto Code Generation with Claude on Issue"

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
        type: string

# Add permissions block
permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  codegen:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Configure Git identity
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 3. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      # 4. Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install anthropic requests

      # 5. Create a new branch named "claude-pr/issue-<number>" from origin/main
      - name: Create Issue Branch
        id: create_branch
        run: |
          ISSUE_NUMBER=${{ inputs.issue_number }}
          BRANCH_NAME="claude-pr/issue-${ISSUE_NUMBER}"
          
          # Create new branch from origin/main without checking it out
          git fetch origin main
          git branch "$BRANCH_NAME" origin/main
          git checkout "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT

      # 6. Generate code using Claude via Python script
      - name: Generate code with Claude
        id: generate_code
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ inputs.issue_number }}
          REPO: ${{ github.repository }}
          PYTHONUNBUFFERED: 1
        run: |
          # Enable debug logging
          export PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}"
          export PYTHONIOENCODING=utf-8
          python -u .github/scripts/generate_code.py
          
          # Check for generated files
          if [ ! -d ".github/generated" ]; then
            echo "Error: Generated code directory not found"
            exit 1
          fi
          
          # List all generated files
          echo "Generated files:"
          find .github/generated -type f -exec ls -l {} \;
          
          # Show preview of each generated file
          for file in $(find .github/generated -type f -name "*.py" -o -name "*.yml"); do
            echo "Preview of ${file}:"
            head -n 5 "${file}"
            echo "---"
          done

      # After generating code but before creating PR
      - name: Save workflow data
        run: |
          if [ -f ".github/generated/metadata.json" ]; then
            cp .github/generated/metadata.json ./workflow-data.json
          else
            echo "{\"issue_number\": \"${{ inputs.issue_number }}\"}" > workflow-data.json
          fi

      - name: Upload workflow data
        uses: actions/upload-artifact@v3
        with:
          name: workflow-data
          path: workflow-data.json

      # 7. Commit & push the generated file
      - name: Commit changes
        run: |
          BRANCH_NAME=${{ steps.create_branch.outputs.BRANCH_NAME }}
          git add .
          git commit -m "Auto-generated code for issue #${{ inputs.issue_number }}"
          git push origin "$BRANCH_NAME"

      # 8. Create Pull Request using GitHub API directly
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.create_branch.outputs.BRANCH_NAME }}
        run: |
          # Create the pull request using GitHub API
          PR_RESPONSE=$(curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{
              "title": "Auto-generated code for Issue #${{ inputs.issue_number }}",
              "body": "This pull request was created automatically from Issue #${{ inputs.issue_number }}.",
              "head": "'$BRANCH_NAME'",
              "base": "main"
            }')
          
          # Check if PR was created successfully
          if [ "$(echo $PR_RESPONSE | jq -r '.id')" = "null" ]; then
            echo "Error creating PR: $PR_RESPONSE"
            exit 1
          fi
          
          echo "Pull request created successfully"
