name: "Auto Code Generation with Claude on Issue"

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
        type: string
  issues:
    types: [assigned]

# Add permissions block
permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  generate:
    # Only run if workflow dispatch or if assigned to yourself
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issues' && github.event.assignee.login == 'johntrue15')
    runs-on: ubuntu-latest
    
    steps:
      - name: Set issue number
        id: set-issue
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "issue_number=${{ github.event.inputs.issue_number }}" >> $GITHUB_OUTPUT
          else
            echo "issue_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.WORKFLOW_PAT }}

      - name: Set up branch
        id: set-branch
        run: |
          BRANCH_NAME="claude-pr/issue-${{ steps.set-issue.outputs.issue_number }}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          
          # Create and checkout new branch
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -b $BRANCH_NAME

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install anthropic PyGithub

      - name: Create directories
        run: |
          mkdir -p .github/generated/workflows
          mkdir -p .github/generated/scripts
          mkdir -p .github/generated/.github/workflows
          mkdir -p .github/generated/.github/scripts

      - name: Generate code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          GITHUB_API_URL: ${{ github.api_url }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
        run: |
          # Debug environment variables
          echo "Checking environment variables:"
          echo "GITHUB_TOKEN: ${GITHUB_TOKEN:+set}"
          echo "ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:+set}"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          
          # Get issue body
          ISSUE_BODY=$(gh issue view ${{ steps.set-issue.outputs.issue_number }} --json body -q .body)
          echo "Issue body retrieved"
          
          # Run code generation with debug
          echo "Running generate_code.py..."
          python -u .github/scripts/generate_code.py "$ISSUE_BODY" ${{ steps.set-issue.outputs.issue_number }}

      - name: Create metadata
        run: |
          # Create metadata.json with generated files
          echo '{"generated_files": [' > .github/generated/metadata.json
          first=true
          
          # Add workflow files
          for f in .github/generated/workflows/*.yml; do
            if [ -f "$f" ]; then
              if [ "$first" = false ]; then echo "," >> .github/generated/metadata.json; fi
              echo "\"workflows/$(basename $f)\"" >> .github/generated/metadata.json
              first=false
            fi
          done
          
          # Add script files
          for f in .github/generated/scripts/*.py; do
            if [ -f "$f" ]; then
              if [ "$first" = false ]; then echo "," >> .github/generated/metadata.json; fi
              echo "\"scripts/$(basename $f)\"" >> .github/generated/metadata.json
              first=false
            fi
          done
          
          echo ']' >> .github/generated/metadata.json
          
          cat .github/generated/metadata.json

      - name: Commit and push
        run: |
          git add .github/generated
          git commit -m "Generated code files for issue #${{ steps.set-issue.outputs.issue_number }}"
          git push origin ${{ steps.set-branch.outputs.branch_name }}

      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
        run: |
          # Create PR
          gh pr create \
            --base main \
            --head ${{ steps.set-branch.outputs.branch_name }} \
            --title "Code updates for issue #${{ steps.set-issue.outputs.issue_number }}" \
            --body "Generated code updates for issue #${{ steps.set-issue.outputs.issue_number }}"

      # After generating code but before creating PR
      - name: Save workflow data
        run: |
          if [ -f ".github/generated/metadata.json" ]; then
            cp .github/generated/metadata.json ./workflow-data.json
          else
            echo "{\"issue_number\": \"${{ steps.set-issue.outputs.issue_number }}\"}" > workflow-data.json
          fi

      - name: Upload workflow data
        uses: actions/upload-artifact@v3
        with:
          name: workflow-data
          path: workflow-data.json

      # Save artifacts
      - name: Save Claude conversation
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: claude-conversation
          path: |
            .github/generated/claude_conversation.json
            .github/generated/claude_conversation_error.json
          if-no-files-found: warn
