name: "Code Review and Analysis"

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
        type: string
  workflow_run:
    workflows: ["Auto Code Generation with Claude on Issue"]
    types: [completed]

permissions: write-all

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set branch name
        id: set-branch
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            BRANCH_NAME="claude-pr/issue-${{ github.event.inputs.issue_number }}"
          else
            BRANCH_NAME="${{ github.event.workflow_run.head_branch }}"
          fi
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "Using branch: $BRANCH_NAME"

      # First checkout the issue branch
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.set-branch.outputs.branch_name }}
          persist-credentials: true
          token: ${{ secrets.WORKFLOW_PAT }}  # Use PAT for checkout

      # Then checkout main branch files
      - uses: actions/checkout@v4
        with:
          ref: main
          path: main-files

      # Set up the directory structure
      - name: Setup directories
        run: |
          # Create necessary directories
          mkdir -p .github/{main,generated,scripts}
          
          # Copy relevant files from main to .github/main
          cp -r main-files/.github/scripts .github/main/ || true
          cp -r main-files/.github/workflows .github/main/ || true
          
          # Copy analyze_code.py from main to workspace
          cp main-files/.github/scripts/analyze_code.py .github/scripts/ || true
          
          # Copy files to be combined to .github/generated
          cp -r .github/workflows .github/generated/ || true
          cp -r .github/scripts .github/generated/ || true
          
          rm -rf main-files
          
          # Debug directory structure
          echo "==== Full directory structure ===="
          find . -type f
          
          echo "==== Contents of .github/scripts ===="
          ls -la .github/scripts/ || echo "scripts dir not found"
          
          echo "==== Contents of .github/main ===="
          ls -la .github/main/ || echo "main dir not found"
          
          echo "==== Contents of .github/generated ===="
          ls -la .github/generated/ || echo "generated dir not found"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install anthropic tenacity PyGithub
          
      - name: Process branch
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Processing issue #${{ github.event.inputs.issue_number }}"
          else
            echo "Processing workflow run from Claude automation"
          fi

      - name: Analyze code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # Verify generated files exist
          if [ ! -d ".github/generated" ]; then
            echo "Error: .github/generated directory not found"
            exit 1
          fi
          
          # Run analyze_code.py
          python .github/scripts/analyze_code.py
          
          # Create staging directory with complete file structure
          mkdir -p staging/.github/{workflows,scripts}
          
          # Copy files preserving directory structure
          if [ -f ".github/generated/complete/.github/workflows/combined_ct_images_to_text.yml" ]; then
            cp ".github/generated/complete/.github/workflows/combined_ct_images_to_text.yml" "staging/.github/workflows/"
          fi
          
          if [ -f ".github/generated/complete/.github/scripts/url_screenshot_check.py" ]; then
            cp ".github/generated/complete/.github/scripts/url_screenshot_check.py" "staging/.github/scripts/"
          fi
          
          # Verify staging contents
          echo "Staging directory contents:"
          find staging -type f
          
          # Verify files exist before commit
          if [ ! -f "staging/.github/workflows/combined_ct_images_to_text.yml" ] || \
             [ ! -f "staging/.github/scripts/url_screenshot_check.py" ]; then
            echo "Error: Required files not found in staging"
            exit 1
          fi

      - name: Commit combined files
        env:
          WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
        run: |
          # Debug git status
          echo "Current branch:"
          git branch
          echo "Remote URL:"
          git remote -v
          
          # Copy files from staging to their final locations
          cp -r staging/.github/* .github/
          
          # Configure git with PAT for workflow push
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${WORKFLOW_PAT}@github.com/${{ github.repository }}.git
          
          # Add and commit the changes
          git add .github/workflows/combined_ct_images_to_text.yml
          git add .github/scripts/url_screenshot_check.py
          
          # Commit and push
          git commit -m "Combined code updates for issue #${{ github.event.inputs.issue_number || github.event.workflow_run.pull_requests[0].number }}"
          git push origin HEAD:${{ steps.set-branch.outputs.branch_name }}

      - name: Add review comment
        if: github.event_name == 'workflow_run'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f ".github/generated/review_comment.md" ]; then
            gh pr comment ${{ github.event.workflow_run.pull_requests[0].number }} -F .github/generated/review_comment.md
          fi

      - name: Show review comment
        if: github.event_name == 'workflow_dispatch' 
        run: |
          if [ -f ".github/generated/review_comment.md" ]; then
            echo "Review comment contents:"
            cat ".github/generated/review_comment.md"
          else
            echo "No review comment generated"
          fi
