name: "Code Review and Analysis"

on:
  workflow_run:
    workflows: ["Auto Code Generation with Claude on Issue"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for file comparisons

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      # Download artifacts from the triggering workflow
      - name: Download workflow artifacts
        id: download_artifacts
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: claude-conversation
          path: artifacts
          search_artifacts: true
          if_no_artifact_found: warn

      # Also download workflow-data to get issue number
      - name: Download workflow data
        id: download_data
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: workflow-data
          path: workflow-data
          search_artifacts: true
          if_no_artifact_found: warn

      # Verify artifacts and extract issue number
      - name: Process artifacts
        id: process
        run: |
          # Check for claude conversation
          if [ ! -d "artifacts" ] || [ -z "$(ls -A artifacts)" ]; then
            echo "::error::Claude conversation artifact not found"
            exit 1
          fi
          
          # Try different methods to get issue number
          if [ -f "workflow-data/workflow-data.json" ]; then
            # From workflow data
            ISSUE_NUMBER=$(cat workflow-data/workflow-data.json | jq -r .issue_number)
          elif [ -f "artifacts/claude_conversation.json" ]; then
            # From conversation data
            ISSUE_NUMBER=$(cat artifacts/claude_conversation.json | jq -r .issue_number)
          else
            # From workflow run
            ISSUE_NUMBER=$(echo "${{ github.event.workflow_run.head_branch }}" | grep -oE '[0-9]+$')
          fi
          
          if [ -z "$ISSUE_NUMBER" ] || [ "$ISSUE_NUMBER" = "null" ]; then
            echo "::error::Could not determine issue number"
            exit 1
          fi
          
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
          echo "Processing issue #$ISSUE_NUMBER"

      - name: Get PR and analyze code
        id: analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ steps.process.outputs.issue_number }}
        run: |
          # Find the PR branch
          BRANCH_NAME="claude-pr/issue-${ISSUE_NUMBER}"
          
          # Checkout the PR branch
          git fetch origin "$BRANCH_NAME" || {
            echo "Error: Could not fetch branch $BRANCH_NAME"
            exit 1
          }
          
          git checkout "$BRANCH_NAME" || {
            echo "Error: Could not checkout branch $BRANCH_NAME"
            exit 1
          }
          
          # Run analysis
          python .github/scripts/analyze_code.py \
            --issue "$ISSUE_NUMBER" \
            --branch "$BRANCH_NAME" \
            --repo "${{ github.repository }}" \
            --artifacts-dir "artifacts"

      - name: Upload combined code
        run: |
          # Verify directory exists and contains files
          if [ ! -d ".github/generated/complete" ]; then
            echo "Error: Output directory not found"
            exit 1
          fi
          
          # List generated files
          echo "Generated files:"
          find .github/generated/complete -type f
          
          # Count files
          file_count=$(find .github/generated/complete -type f | wc -l)
          if [ "$file_count" -eq 0 ]; then
            echo "Error: No files found in output directory"
            exit 1
          fi
          
          echo "Found $file_count generated files"
          
          # Copy files to a staging directory with simpler structure
          mkdir -p staging
          cp -r .github/generated/complete/* staging/
          
          # List staging directory
          echo "Staging directory contents:"
          ls -R staging/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: combined-code
          path: staging
          if-no-files-found: error
          compression-level: 0  # No compression for text files
          overwrite: true
          retention-days: 90

      - name: Add review comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f ".github/generated/review_comment.md" ]; then
            # Find PR number for the branch
            PR_NUMBER=$(gh pr list --head "$BRANCH_NAME" --json number -q '.[0].number')
            if [ ! -z "$PR_NUMBER" ]; then
              gh pr comment "$PR_NUMBER" --body-file ".github/generated/review_comment.md"
            else
              echo "No PR found for branch $BRANCH_NAME"
              exit 1
            fi
          fi
