name: "Code Review and Analysis"

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
        type: string
  workflow_run:
    workflows: ["Auto Code Generation with Claude on Issue"]
    types: [completed]


permissions: write-all

jobs:
  analyze:
    # Only run if the triggering workflow succeeded
    if: >-
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    
    steps:
      - name: Debug workflow trigger
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow run head branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Workflow run head sha: ${{ github.event.workflow_run.head_sha }}"

      - name: Set branch name
        id: set-branch
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            ISSUE_NUM="${{ github.event.inputs.issue_number }}"
          else
            # Extract issue number from the triggering workflow's branch name
            BRANCH_NAME="${{ github.event.workflow_run.head_branch }}"
            if [[ "$BRANCH_NAME" =~ claude-pr/issue-([0-9]+) ]]; then
              ISSUE_NUM="${BASH_REMATCH[1]}"
            else
              echo "Error: Could not extract issue number from branch name: $BRANCH_NAME"
              exit 1
            fi
          fi
          
          BRANCH_NAME="claude-pr/issue-${ISSUE_NUM}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "issue_number=$ISSUE_NUM" >> $GITHUB_OUTPUT
          echo "Using branch: $BRANCH_NAME for issue #$ISSUE_NUM"

      # First checkout issue branch to get repository structure
      - name: Checkout issue branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.set-branch.outputs.branch_name }}
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.WORKFLOW_PAT }}

      # Then checkout main branch files to a subdirectory
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main-files
          token: ${{ secrets.WORKFLOW_PAT }}
          fetch-depth: 1

      # Create required directories if they don't exist
      - name: Create directories
        run: |
          mkdir -p .github/generated/workflows
          mkdir -p .github/generated/scripts
          mkdir -p staging/.github/workflows
          mkdir -p staging/.github/scripts
          
          echo "Directory structure:"
          ls -R .github/
          ls -R staging/

      # Verify branch and files
      - name: Verify setup
        run: |
          echo "Current branch:"
          git branch
          
          echo "Generated files location:"
          ls -la .github/generated/
          
          echo "Main files location:"
          ls -la main-files/.github/
          
          # Ensure we're on the correct branch
          if [ "$(git rev-parse --abbrev-ref HEAD)" != "${{ steps.set-branch.outputs.branch_name }}" ]; then
            echo "Switching to correct branch"
            git checkout ${{ steps.set-branch.outputs.branch_name }}
          fi

      # Set up Python and dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pathlib anthropic

      # Set up the directory structure
      - name: Setup directories
        run: |
          # Debug current state
          echo "Current workspace:"
          pwd
          ls -la
          
          echo "Main files location:"
          ls -la main-files/ || echo "main-files not found"
          
          # Create necessary directories
          mkdir -p .github/generated
          
          # Verify main files checkout
          if [ ! -d "main-files/.github/scripts" ]; then
            echo "Error: main-files scripts directory not found"
            echo "Contents of main-files:"
            find main-files -type f
            exit 1
          fi
          
          # Copy analyze_code.py from main to workspace root
          if [ -f "main-files/.github/scripts/analyze_code.py" ]; then
            cp main-files/.github/scripts/analyze_code.py ./analyze_code.py
            echo "Copied analyze_code.py to workspace root"
          else
            echo "Error: analyze_code.py not found in main-files"
            echo "Contents of main-files/.github/scripts:"
            ls -la main-files/.github/scripts/
            exit 1
          fi
          
          # Debug final structure
          echo "Final workspace structure:"
          find . -maxdepth 3 -type f
          
          echo "Contents of .github/generated:"
          ls -la .github/generated/

      # Run the analysis using analyze_code from main
      - name: Analyze code
        id: analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # Create log directory
          mkdir -p logs
          
          # Run analyze_code.py and capture output
          echo "Running code analysis..."
          python analyze_code.py 2>&1 | tee logs/analyze.log
          
          # Check if analysis was successful
          if [ -f "logs/analyze.log" ]; then
            echo "Analysis log:"
            cat logs/analyze.log
            
            # Check for Claude responses in log
            if grep -q "Got response from Claude" logs/analyze.log; then
              echo "Claude analysis complete"
            else
              echo "Warning: No Claude responses found in log"
            fi
          fi
          
          # Verify staging contents
          echo "Staging directory contents:"
          find staging -type f
          
          # Save log as artifact
          echo "logs_path=logs/analyze.log" >> $GITHUB_OUTPUT

      # Upload analysis logs
      - name: Upload analysis logs
        uses: actions/upload-artifact@v3
        with:
          name: analysis-logs
          path: logs/analyze.log

      # Commit the changes
      - name: Commit combined files
        env:
          WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
        run: |
          # Debug git status
          echo "Current branch:"
          git branch
          echo "Remote URL:"
          git remote -v
          
          # Debug staging contents
          echo "Staging contents:"
          find staging -type f || echo "No files in staging"
          
          # Copy files from staging to their final locations if staging exists
          if [ -d "staging/.github" ]; then
            cp -r staging/.github/* .github/
            echo "Copied files from staging to .github"
          fi
          
          # Configure git
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${WORKFLOW_PAT}@github.com/${{ github.repository }}.git
          
          # Read metadata if it exists
          if [ -f ".github/generated/metadata.json" ]; then
            echo "Reading metadata file..."
            cat .github/generated/metadata.json
            
            # Add files from metadata
            while IFS= read -r file; do
              # Remove quotes and whitespace
              file=$(echo "$file" | tr -d '"' | tr -d ' ')
              if [ ! -z "$file" ]; then
                echo "Adding file: .github/$file"
                git add ".github/$file"
              fi
            done < <(jq -r '.generated_files[]' .github/generated/metadata.json)
          else
            echo "No metadata.json found, adding all files in .github/generated"
            git add .github/generated/
          fi
          
          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          # Create commit message
          commit_msg="Code review updates for issue #${{ steps.set-branch.outputs.issue_number }}"
          
          # Commit and push
          git commit -m "$commit_msg"
          git push origin HEAD:${{ steps.set-branch.outputs.branch_name }}

      - name: Add review comment
        if: github.event_name == 'workflow_run'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f ".github/generated/review_comment.md" ]; then
            gh pr comment ${{ github.event.workflow_run.pull_requests[0].number }} -F .github/generated/review_comment.md
          fi

      - name: Show review comment
        if: github.event_name == 'workflow_dispatch' 
        run: |
          if [ -f ".github/generated/review_comment.md" ]; then
            echo "Review comment contents:"
            cat ".github/generated/review_comment.md"
          else
            echo "No review comment generated"
          fi
