name: "Code Review and Analysis"

on:
  workflow_run:
    workflows: ["Auto Code Generation with Claude on Issue"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for file comparisons

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      # Download artifacts from the triggering workflow
      - name: Download workflow artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: claude-conversation
          path: artifacts
          search_artifacts: true  # Search in case name is different
          if_no_artifact_found: warn

      # Also download workflow-data to get issue number
      - name: Download workflow data
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: workflow-data
          path: workflow-data
          search_artifacts: true
          if_no_artifact_found: error

      - name: List artifacts
        run: |
          echo "Contents of artifacts directory:"
          ls -R artifacts/
          echo "Contents of workflow-data directory:"
          ls -R workflow-data/

      - name: Get PR and analyze code
        id: analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the issue number from workflow data
          if [ ! -f "workflow-data/workflow-data.json" ]; then
            echo "Error: workflow-data.json not found"
            exit 1
          fi
          
          ISSUE_NUMBER=$(cat workflow-data/workflow-data.json | jq -r .issue_number)
          if [ -z "$ISSUE_NUMBER" ] || [ "$ISSUE_NUMBER" = "null" ]; then
            echo "Error: Could not get issue number from workflow data"
            exit 1
          fi
          
          echo "Processing issue #$ISSUE_NUMBER"
          
          # Find the PR branch
          BRANCH_NAME="claude-pr/issue-${ISSUE_NUMBER}"
          
          # Checkout the PR branch
          git fetch origin "$BRANCH_NAME" || {
            echo "Error: Could not fetch branch $BRANCH_NAME"
            exit 1
          }
          
          git checkout "$BRANCH_NAME" || {
            echo "Error: Could not checkout branch $BRANCH_NAME"
            exit 1
          }
          
          # Run analysis
          python .github/scripts/analyze_code.py \
            --issue "$ISSUE_NUMBER" \
            --branch "$BRANCH_NAME" \
            --repo "${{ github.repository }}" \
            --artifacts-dir "artifacts"

      - name: Upload combined code
        uses: actions/upload-artifact@v3
        with:
          name: combined-code
          path: .github/generated/complete
          if-no-files-found: error

      - name: Add review comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f ".github/generated/review_comment.md" ]; then
            # Find PR number for the branch
            PR_NUMBER=$(gh pr list --head "$BRANCH_NAME" --json number -q '.[0].number')
            if [ ! -z "$PR_NUMBER" ]; then
              gh pr comment "$PR_NUMBER" --body-file ".github/generated/review_comment.md"
            else
              echo "No PR found for branch $BRANCH_NAME"
              exit 1
            fi
          fi
