name: "Code Review and Analysis"

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'claude-pr/issue-*'
      - 'testing/issue-*'

permissions:
  contents: write
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'claude-pr/issue-') || startsWith(github.head_ref, 'testing/issue-')
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for file comparisons

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Download workflow artifacts
        uses: actions/download-artifact@v3
        with:
          name: claude-conversation
          path: artifacts

      - name: Analyze and combine code
        id: analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the issue number from branch name
          BRANCH_NAME="${{ github.head_ref }}"
          ISSUE_NUMBER=$(echo $BRANCH_NAME | grep -oE '[0-9]+$')
          
          # Run analysis
          python .github/scripts/analyze_code.py \
            --issue $ISSUE_NUMBER \
            --branch "$BRANCH_NAME" \
            --repo "${{ github.repository }}" \
            --artifacts-dir "artifacts"

      - name: Upload combined code
        uses: actions/upload-artifact@v3
        with:
          name: combined-code
          path: .github/generated/complete
          if-no-files-found: error

      - name: Add review comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f ".github/generated/review_comment.md" ]; then
            gh pr comment "${{ github.event.pull_request.number }}" --body-file ".github/generated/review_comment.md"
          fi
