name: MorphoSource CT API Pipeline

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  process:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Process MorphoSource records via API
        id: process
        env:
          MORPHOSOURCE_API_KEY: ${{ secrets.MORPHOSOURCE_API_KEY }}
        run: |
          python .github/scripts/process_morphosource_records.py

      - name: Commit updated MorphoSource state
        if: >-
          steps.process.outputs.delta != '0' || steps.process.outputs.records_processed != '0'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add morphosource_xray_count.txt .github/morphosource_state.json analysis_summary.md
          git commit -m "Update MorphoSource API analysis" || echo "No changes to commit"
          git push

      - name: Upload analysis artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: morphosource-api-analysis
          path: |
            analysis_summary.md
            downloads/
          retention-days: 30
