name: CT Images to Text

on:
  workflow_run:
    workflows: ["Parse MorphoSource Data"]
    types: [completed]

jobs:
  ct_image_text_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser libnss3 libgbm1 libasound2
          pip install --upgrade pip
          pip install openai selenium pillow webdriver-manager urllib3

      - name: Fetch MorphoSource Release
        id: fetch_release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          echo "Fetching releases from this repo..."
          releases=$(curl -sSL -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/releases?per_page=100")
          
          # Get latest morphosource release
          morphosource_release=$(echo "$releases" | python3 .github/scripts/get_morphosource_release.py)
          
          # Extract data
          body=$(echo "$morphosource_release" | jq -r '.body // empty')
          tag_name=$(echo "$morphosource_release" | jq -r '.tag_name // empty')
          
          # Extract URL from body
          url=$(echo "$body" | python3 .github/scripts/extract_url.py)
          
          if [ -z "$tag_name" ] || [[ "$tag_name" != morphosource-updates-* ]]; then
            echo "No morphosource-updates release found"
            echo "is_morphosource=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          
          echo "Found morphosource release: $tag_name"
          echo "is_morphosource=true" >> "$GITHUB_OUTPUT"
          
          if [ "$url" != "NO_URL_FOUND" ]; then
            echo "morphosource_url=$url" >> "$GITHUB_OUTPUT"
          else
            echo "morphosource_url=" >> "$GITHUB_OUTPUT"
          fi
          
          echo "release_tag=$tag_name" >> "$GITHUB_OUTPUT"

      - name: Generate Timestamp
        id: gen_ts
        if: steps.fetch_release.outputs.is_morphosource == 'true'
        run: |
          TS=$(date +'%Y-%m-%d_%H-%M-%S')
          echo "timestamp=$TS" >> "$GITHUB_OUTPUT"

      - name: Process CT Images
        id: process_images
        if: steps.fetch_release.outputs.is_morphosource == 'true' && steps.fetch_release.outputs.morphosource_url != ''
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MORPHOSOURCE_URL: ${{ steps.fetch_release.outputs.morphosource_url }}
        run: |
          if [ -z "$MORPHOSOURCE_URL" ]; then
            echo "No valid MorphoSource URL found in release."
            exit 1
          fi
          
          mkdir -p screenshots
          python3 .github/scripts/ct_image_to_text.py "$MORPHOSOURCE_URL" screenshots 2>&1 | tee process.log
          
          if [ ! -f "screenshots/*.png" ]; then
            echo "No screenshots were generated. Check process.log for details."
            exit 1
          fi
          
          # Save the analysis output
          echo "description<<EOF" >> "$GITHUB_OUTPUT"
          cat process.log | grep -v "INFO" | grep -v "WARNING" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create Image Analysis Release
        if: steps.fetch_release.outputs.is_morphosource == 'true' && success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: "ct_image_analysis-${{ steps.gen_ts.outputs.timestamp }}"
          release_name: "CT Image Analysis #${{ steps.gen_ts.outputs.timestamp }}"
          body: ${{ steps.process_images.outputs.description }}
          draft: false
          prerelease: false

      - name: Upload Screenshots
        if: steps.fetch_release.outputs.is_morphosource == 'true' && success()
        uses: actions/upload-artifact@v3
        with:
          name: ct-scan-screenshots
          path: screenshots/*.png
          retention-days: 90

      - name: Handle Errors
        if: failure()
        run: |
          echo "Workflow failed. Please check:"
          echo "1. Release tag format"
          echo "2. Valid MorphoSource URL in release body"
          echo "3. WebGL support in Chrome"
          echo "4. Screenshot capture process"
          
          if [ -f "process.log" ]; then
            echo "Process log contents:"
            cat process.log
          fi
          exit 1
