name: CT to Text (on new Morphosource Release)

on:
  release:
    types: [published]

jobs:
  ct_text_job:
    # Only run if the newly published release’s tag_name starts with "morphosource-updates-"
    if: startsWith(github.event.release.tag_name, 'morphosource-updates')
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests beautifulsoup4 openai

      - name: Capture the release body
        id: capture_body
        run: |
          echo "release_body<<EOF" >> $GITHUB_OUTPUT
          echo "${{ github.event.release.body }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run CT to Text
        id: ct2text
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          # Save the release body to a local file
          echo "${{ steps.capture_body.outputs.release_body }}" > release_body.txt
          
          # Run the Python script with that file, capturing stdout to ct_output.txt
          python .github/scripts/ct_to_text.py release_body.txt > ct_output.txt
          
          # Convert ct_output.txt into a GitHub Actions output named 'description'
          echo "description<<EOF" >> $GITHUB_OUTPUT
          cat ct_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create or Update Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: "ct-to-text-${{ github.run_number }}"
          release_name: "CT to Text #${{ github.run_number }}"
          body: ${{ steps.ct2text.outputs.description }}
          draft: false
          prerelease: false
