name: CT to Text

on:
  workflow_run:
    workflows: ["Parse MorphoSource Data"]  # must match the name: field in parse_morphosource_data.yml
    types: [completed]

jobs:
  ct_text_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install requests beautifulsoup4 openai

      - name: Fetch Latest Release
        id: fetch_release
        env:
          # Use your GITHUB_TOKEN or a custom token with repo/read permissions
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          echo "Fetching the latest morphosource-updates- release..."
          # We'll call /releases/latest for simplicity, assuming your "latest" is always morphosource-updates-*
          response=$(curl -sSL -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest)

          echo "$response" > latest_release.json
          echo "Response: $response"

          # Extract the 'body' from JSON
          body=$(echo "$response" | python -c "import sys, json; print(json.load(sys.stdin)['body'])")

          # Make 'release_body' an output for the next step
          echo "release_body<<EOF" >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run CT to Text
        id: ct2text
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Save the release body to a file
          echo "${{ steps.fetch_release.outputs.release_body }}" > release_body.txt

          # Run your script, capture output
          python .github/scripts/ct_to_text.py release_body.txt > ct_output.txt

          # Expose it as an Actions output 'description'
          echo "description<<EOF" >> $GITHUB_OUTPUT
          cat ct_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create or Update Release with AI Summary
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: "ct-to-text-analysis-${{ github.run_number }}"
          release_name: "CT to Text Analysis #${{ github.run_number }}"
          body: ${{ steps.ct2text.outputs.description }}
          draft: false
          prerelease: false
