name: CT to Text from Latest Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"   # run daily at 3 AM if desired

jobs:
  ct_text_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4 openai
          # If you have a specific version of openai or special library for "o1-mini", adapt here

      - name: Run CT to Text
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: python .github/scripts/ct_to_text.py

      # Optional: Create a release with the generated text if you want
      # - You can parse the script output as needed
