name: CT to Text Generation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # e.g., daily at 3 AM

jobs:
  ct_text_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 openai

      - name: Run CT to Text
        id: ct2text
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Run the script and capture stdout to a file
          python .github/scripts/ct_to_text.py > ct_output.txt

          # Convert the file contents into a GitHub Actions output named 'description'
          echo "description<<EOF" >> $GITHUB_OUTPUT
          cat ct_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create or Update Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: "ct-to-text-updates-${{ github.run_number }}"
          release_name: "CT to Text Summaries #${{ github.run_number }}"
          body: ${{ steps.ct2text.outputs.description }}
          draft: false
          prerelease: false
