name: Daily MorphoSource Check
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-and-collect:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch complete history
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Create data directory
      run: mkdir -p data
        
    - name: Run daily check
      id: daily-check
      run: |
        python .github/scripts/daily.py
      continue-on-error: true

    - name: Collect new records
      id: collect
      if: steps.daily-check.outcome == 'failure'  # Only run if new records found
      run: |
        python .github/scripts/collect.py
        
    - name: Create Release
      if: always()  # Create release whether there are new records or not
      uses: softprops/action-gh-release@v1
      with:
        name: "Daily MorphoSource Check ${{ github.run_number }}"
        tag_name: "check-${{ github.run_number }}"
        body_path: ${{ steps.daily-check.outcome == 'failure' && 'data/release_notes.txt' || format('Results of check {0}: No new records found', github.run_number) }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push if changes
      if: steps.daily-check.outcome == 'failure'  # Only if new records were found
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/morphosource_data_complete.json
        git commit -m "Update MorphoSource data [skip ci]" || exit 0
        git push

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: execution-logs
        path: |
          data/daily_extractor.log
          data/collector.log
