name: Daily MorphoSource Check
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-and-collect:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch complete history
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Create data directory
      run: mkdir -p data
        
    - name: Run daily check
      id: daily-check
      run: |
        python .github/scripts/daily.py
      continue-on-error: true

    - name: Generate timestamp
      id: timestamp
      run: |
        echo "value=$(date +'%Y-%m-%d_%H-%M-%S')" >> "$GITHUB_OUTPUT"

    - name: Collect new records
      id: collect
      if: steps.daily-check.outcome == 'failure'  # Only run if new records found
      run: |
        python .github/scripts/collect.py

    - name: Create Release
      if: always()
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: "MorphoSource Check #${{ steps.timestamp.outputs.value }}"
        tag_name: "morphosource-check-${{ steps.timestamp.outputs.value }}"
        body: ${{ steps.daily-check.outcome == 'failure' && steps.collect.outputs.summary || 'No new records found' }}
        draft: false
        prerelease: false

    - name: Commit and push if changes
      if: steps.daily-check.outcome == 'failure'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/morphosource_data_complete.json
        git commit -m "Update MorphoSource data [skip ci]" || exit 0
        git push

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: execution-logs
        path: |
          data/daily_extractor.log
          data/collector.log
