name: 2D or 3D Selenium Fullscreen Test
on:
  workflow_dispatch:
    inputs:
      media_id:
        description: 'MorphoSource media ID to analyse (optional)'
        required: false
        type: string
      download_reason:
        description: 'Reason to provide when downloading 3D media assets'
        required: false
        type: string
  push:
    branches: [ "main" ]
    paths:
     - "src/**"
     - "tests/**"
  pull_request:
    branches: [ "main" ]

jobs:
  run-selenium-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install selenium webdriver-manager requests

      - name: Select MorphoSource media record
        id: select-media
        env:
          MEDIA_ID_INPUT: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.media_id || '' }}
          DOWNLOAD_REASON_INPUT: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.download_reason || '' }}
        run: |
          set -eo pipefail
          ARGS=()
          if [ -n "$MEDIA_ID_INPUT" ]; then
            ARGS+=(--media-id "$MEDIA_ID_INPUT")
          fi
          python .github/scripts/dimension_media_fetcher.py \
            "${ARGS[@]}" \
            --download-reason "${DOWNLOAD_REASON_INPUT:-Automated testing via GitHub Actions}" \
            --artifact-dir artifacts \
            --output-json artifacts/dimension_media_summary.json

      - name: Install and setup Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg2 unzip
          # Install Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
      
      - name: Run Selenium test
        env:
          MEDIA_URL: ${{ steps.select-media.outputs.media_url }}
          MEDIA_DIMENSION: ${{ steps.select-media.outputs.media_dimension }}
        run: |
          set -eo pipefail
          if [ -z "$MEDIA_URL" ]; then
            echo "::error::No media URL was produced by the selection step."
            exit 1
          fi
          if [[ "$MEDIA_DIMENSION" == "3d" ]]; then
            python .github/scripts/selenium_fullscreen_test3D.py --url "$MEDIA_URL"
          else
            python .github/scripts/selenium_fullscreen_test2D.py --url "$MEDIA_URL"
          fi

      - name: Upload media metadata artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: morphosource_media_assets
          if-no-files-found: ignore
          path: |
            ${{ steps.select-media.outputs.summary_path }}
            ${{ steps.select-media.outputs.manifest_path }}
            ${{ steps.select-media.outputs.download_dir }}

      - name: Upload screenshot artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fullscreen_screenshot
          if-no-files-found: ignore
          path: |
            fullscreen_screenshot_2D.png
            fullscreen_screenshot_3D.png
