name: Monthly MorphoSource Collection
on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight on the first of each month
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write
  id-token: write
  actions: read
  attestations: write

jobs:
  monthly-collection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch complete history
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Create data directory
      run: mkdir -p data

    - name: Generate timestamp
      id: timestamp
      run: |
        echo "value=$(date +'%Y-%m-%d_%H-%M-%S')" >> "$GITHUB_OUTPUT"

    - name: Run monthly collection
      id: collect
      run: |
        python .github/scripts/monthly.py

    - name: Generate Attestation
      uses: actions/attest@v2.1.0
      id: attest
      with:
        subject-path: data/morphosource_data_complete.json
        predicate-type: 'https://in-toto.io/attestation/release/v0.1'
        output-path: monthly_collection_attestation.json
        predicate: |
          {
            "purl": "pkg:github/${{ github.repository }}",
            "version": "${{ github.sha }}",
            "metadata": {
              "buildInvocationId": "${{ github.run_id }}",
              "completeness": {
                "parameters": true,
                "environment": true,
                "materials": true
              }
            }
          }

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: "Monthly MorphoSource Collection #${{ steps.timestamp.outputs.value }}"
        tag_name: "monthly-collection-${{ steps.timestamp.outputs.value }}"
        body_path: data/monthly_release_notes.txt
        files: |
          data/morphosource_data_complete.json
          monthly_collection_attestation.json

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/morphosource_data_complete.json
        git commit -m "Monthly MorphoSource data update [skip ci]" || exit 0
        git push

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: monthly-execution-logs
        path: |
          data/monthly_collector.log
