name: Parquet Data Processor

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

permissions:
  contents: write
  id-token: write

jobs:
  process-urls:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas pyarrow tqdm
          
      - name: Generate Timestamp
        id: timestamp
        run: |
          TS=$(date +'%Y-%m-%d_%H-%M-%S')
          echo "timestamp=$TS" >> $GITHUB_OUTPUT
          
      - name: Process URLs
        id: process_urls
        run: |
          python .github/scripts/parquet_processor.py \
            --output-dir data/parquet/${{ steps.timestamp.outputs.timestamp }} \
            --batch-size 100 \
            --log-file data/parquet/${{ steps.timestamp.outputs.timestamp }}/processor.log
            
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: parquet-data-${{ steps.timestamp.outputs.timestamp }}
          path: data/parquet/${{ steps.timestamp.outputs.timestamp }}
          
      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/parquet/${{ steps.timestamp.outputs.timestamp }}
          git commit -m "Parquet data processing [${{ steps.timestamp.outputs.timestamp }}]"
          git push 