name: Parse MorphoSource Data

on:
  schedule:
    # Run every 12 hours (UTC time by default).
    - cron: "0 */12 * * *"
  # Allows manual runs from the GitHub Actions tab if desired
  workflow_dispatch:

jobs:
  scrape_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Scraper
        id: scraper
        run: python .github/scripts/scrape_morphosource.py

      - name: Create or Update Release
        if: steps.scraper.outputs.new_data == 'true'
        uses: actions/create-release@v1
        with:
          tag_name: 'morphosource-updates'
          release_name: 'MorphoSource Updates'
          body: |
            A new increase in **X-ray Computed Tomography** records was found on MorphoSource.
            
            ${{ steps.scraper.outputs.details }}
          draft: false
          prerelease: false
