name: Parse MorphoSource Data

on:
  schedule:
    # Runs every 12 hours: 0th minute, every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write  # Needed to commit changes (last_count.txt) back to the repo

jobs:
  scrape_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Needed so we can push commits

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Scraper
        id: scraper
        run: python .github/scripts/scrape_morphosource.py

      - name: Commit updated last_count.txt
        # Only commit if new_data == 'true'
        if: steps.scraper.outputs.new_data == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .github/last_count.txt
          git commit -m "Update last_count.txt for new records"
          git push

      - name: Create or Update Release
        if: steps.scraper.outputs.new_data == 'true'
        uses: actions/create-release@v1
        env:
          # You can use secrets.MY_GITHUB_TOKEN or a custom personal access token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: morphosource-updates-${{ github.run_number }}
          release_name: "MorphoSource Updates #${{ github.run_number }}"
          body: ${{ steps.scraper.outputs.details }}
          draft: false
          prerelease: false
