name: Parse MorphoSource Data

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  # Allow this workflow to push commits back to the repo.
  contents: write

jobs:
  scrape_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Required so we can push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Scraper
        id: scraper
        run: python .github/scripts/scrape_morphosource.py

      # Commit the updated last_count.txt if new data was found
      - name: Commit updated last_count.txt
        if: steps.scraper.outputs.new_data == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .github/last_count.txt
          git commit -m "Update last_count.txt for new records"
          git push origin HEAD:${{ github.ref_name }}

      - name: Create or Update Release
        if: steps.scraper.outputs.new_data == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # or use secrets.GITHUB_TOKEN
        with:
          tag_name: morphosource-updates-${{ github.run_number }}
          release_name: "MorphoSource Updates #${{ github.run_number }}"
          body: |
            A new increase in **X-ray Computed Tomography** records was found on MorphoSource.

            ${{ steps.scraper.outputs.details }}
          draft: false
          prerelease: false
