name: Automated Screenshot Workflow

on:
  workflow_run:
    # 1) Trigger this workflow after the "CT to Text" workflow completes.
    workflows: ["CT to Text"]
    types: [completed]

jobs:
  screenshot_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # -------------------------------------------------------
      # 1. Check out your repository
      # -------------------------------------------------------
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Log - Checked out repository
        run: echo "Repository has been checked out."

      # -------------------------------------------------------
      # 2. Set up Python
      # -------------------------------------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Log - Python setup complete
        run: echo "Python 3.9 is now set up."

      # -------------------------------------------------------
      # 3. Install Dependencies (including Chrome and Chromedriver)
      # -------------------------------------------------------
      - name: Install Chrome and Chromedriver
        run: |
          echo "Starting installation of Chrome & Chromedriver..."
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
       
