name: Test Daily Check
on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  actions: read
  attestations: write

jobs:
  test-daily-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Set timestamp
      id: timestamp
      run: |
        TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
        echo "timestamp=$TIMESTAMP" >> $GITHUB_ENV
        echo "Timestamp set to: $TIMESTAMP"

    - name: Find Latest Data Directory
      id: find-latest
      run: |
        # Find the latest timestamped directory in data/
        LATEST_DIR=$(find data -maxdepth 1 -type d -name "20*" | sort -r | head -n1 || echo "")
        if [ -z "$LATEST_DIR" ]; then
          echo "No timestamped data directories found"
          exit 1
        fi
        echo "Found latest data directory: $LATEST_DIR"
        echo "dir=$LATEST_DIR" >> $GITHUB_OUTPUT

    - name: Create Test Data
      run: |
        mkdir -p "data/${{ env.timestamp }}"
        python .github/scripts/test_daily.py \
          --source-dir "${{ steps.find-latest.outputs.dir }}" \
          --output-dir "data/${{ env.timestamp }}"

    - name: Run Daily Check
      id: daily-check
      env:
        LATEST_DATA_DIR: ${{ steps.find-latest.outputs.dir }}
        TEST_DATA_DIR: data/${{ env.timestamp }}
      run: |
        python .github/scripts/daily.py --data-dir "$TEST_DATA_DIR"
      continue-on-error: true

    - name: Upload Test Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-daily-logs-${{ env.timestamp }}
        path: |
          data/${{ env.timestamp }}/* 