name: Test MorphoSource Screenshots Analysis
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'MorphoSource URL to process'
        required: true
        default: 'https://www.morphosource.org/concern/media/000704012'
        type: string

jobs:
  process-screenshots:
    runs-on: ubuntu-latest
    
    env:
      PYTHONUNBUFFERED: 1
      DISPLAY: :99
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Setup virtual display
      run: |
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        sleep 2
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libopengl0 mesa-utils chromium-browser libnss3 libgbm1 libasound2t64
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager requests Pillow urllib3 openai
    
    - name: Create test directory
      run: mkdir -p test_screenshots
    
    - name: Create URL file
      run: |
        echo "${{ github.event.inputs.url }}" > url.txt
    
    - name: Process screenshots and analyze
      run: |
        # Verify OpenAI API key is set
        if [ -z "$OPENAI_API_KEY" ]; then
          echo "Error: OPENAI_API_KEY is not set"
          exit 1
        fi
        
        # Run the script
        python .github/scripts/ct_image_to_text.py url.txt test_screenshots | tee analysis_output.txt
      
    - name: List generated files
      if: always()
      run: |
        echo "Generated files:"
        ls -la test_screenshots/*.png || true
        ls -la analysis_output.txt || true
    
    - name: Upload results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: morphosource_results
        path: |
          test_screenshots/*.png
          analysis_output.txt
        retention-days: 7
