name: Test Daily Check
on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  actions: read
  attestations: write

jobs:
  test-daily-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Set timestamps
      id: timestamps
      run: |
        TEST_TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
        DAILY_TIMESTAMP=$(date -d '+1 minute' +'%Y-%m-%d_%H-%M-%S')  # Simulate next minute for daily
        echo "test_timestamp=$TEST_TIMESTAMP" >> $GITHUB_ENV
        echo "daily_timestamp=$DAILY_TIMESTAMP" >> $GITHUB_ENV
        echo "Test timestamp: $TEST_TIMESTAMP"
        echo "Daily timestamp: $DAILY_TIMESTAMP"

    - name: Find Latest Data Directory
      id: find-latest
      run: |
        # Look for either file name
        for FILE in "morphosource_data_complete.json" "updated_morphosource_data.json"; do
          LATEST_DIR=$(find data -maxdepth 2 -type f -name "$FILE" -exec dirname {} \; | sort -r | head -n1 || echo "")
          if [ ! -z "$LATEST_DIR" ]; then
            echo "Found latest data directory: $LATEST_DIR with file: $FILE"
            echo "dir=$LATEST_DIR" >> $GITHUB_OUTPUT
            echo "filename=$FILE" >> $GITHUB_OUTPUT
            break
          fi
        done
        
        if [ -z "$LATEST_DIR" ]; then
          echo "No data files found"
          exit 1
        fi

    - name: Create Test Data
      run: |
        mkdir -p "data/${{ env.test_timestamp }}"
        SOURCE_FILE="${{ steps.find-latest.outputs.dir }}/${{ steps.find-latest.outputs.filename }}"
        
        if [ ! -f "$SOURCE_FILE" ]; then
          echo "Source file not found: $SOURCE_FILE"
          exit 1
        fi
        
        echo "Using source file: $SOURCE_FILE"
        python .github/scripts/test_daily.py \
          --source-dir "${{ steps.find-latest.outputs.dir }}" \
          --output-dir "data/${{ env.test_timestamp }}" \
          --source-file "$SOURCE_FILE"

    - name: Simulate Daily Collection
      run: |
        mkdir -p "data/${{ env.daily_timestamp }}"
        SOURCE_FILE="${{ steps.find-latest.outputs.dir }}/${{ steps.find-latest.outputs.filename }}"
        cp "$SOURCE_FILE" "data/${{ env.daily_timestamp }}/morphosource_data_complete.json"

    - name: Run Daily Check
      id: daily-check
      env:
        LATEST_DATA_DIR: ${{ steps.find-latest.outputs.dir }}
        TEST_DATA_DIR: data/${{ env.test_timestamp }}
        DAILY_OUTPUT_DIR: data/${{ env.daily_timestamp }}
      run: |
        # No need to copy/rename files anymore
        python .github/scripts/daily.py \
          --data-dir "$DAILY_OUTPUT_DIR" \
          --output-dir "$DAILY_OUTPUT_DIR"
      continue-on-error: true

    - name: Create Release Notes
      if: always()
      run: |
        if [ "${{ steps.daily-check.outcome }}" == "success" ]; then
          echo "No new records found" > "data/${{ env.test_timestamp }}/release_notes.txt"
        fi

    - name: Generate Attestation for Test Dataset
      if: steps.daily-check.outcome == 'failure'
      uses: actions/attest@v2.1.0
      id: attest-test
      with:
        subject-path: data/${{ env.test_timestamp }}/morphosource_data_complete.json
        predicate-type: 'https://in-toto.io/attestation/release/v0.1'
        show-summary: true
        predicate: |
          {
            "purl": "pkg:github/${{ github.repository }}",
            "version": "${{ github.sha }}",
            "metadata": {
              "buildInvocationId": "${{ github.run_id }}",
              "completeness": {
                "parameters": true,
                "environment": true,
                "materials": true
              },
              "test_info": {
                "type": "daily_test",
                "timestamp": "${{ env.test_timestamp }}"
              }
            }
          }

    - name: Save Attestation and Update Release Notes
      if: steps.daily-check.outcome == 'failure'
      run: |
        # Get attestation ID from URL in output
        ATT_URL="${{ steps.attest-test.outputs.attestation-url }}"
        ATT_ID=$(echo "$ATT_URL" | grep -o '[0-9]*$' || true)
        
        echo "Attestation URL: $ATT_URL"
        echo "Attestation ID: $ATT_ID"
        
        if [ -z "$ATT_ID" ]; then
          echo "Error: Could not extract attestation ID"
          exit 1
        fi
        
        # Fetch the attestation page and extract SHA256
        DIGEST=$(curl -s "$ATT_URL" | grep -A2 "Subjects" | grep "sha256:" | sed 's/.*sha256:\([a-f0-9]\{64\}\).*/\1/')
        echo "SHA256 Digest: $DIGEST"
        
        # Validate that we got a proper SHA256 (64 hex characters)
        if ! [[ $DIGEST =~ ^[a-f0-9]{64}$ ]]; then
          echo "Error: Invalid SHA256 digest format"
          exit 1
        fi
        
        # Update the release notes with attestation info
        echo -e "\n## Attestation\nTest Dataset: $ATT_URL" >> "data/${{ env.test_timestamp }}/release_notes.txt"

    - name: Create Release
      if: always()
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: "Test Daily Check #${{ env.test_timestamp }}"
        tag_name: "test-daily-${{ env.test_timestamp }}"
        body_path: data/${{ env.test_timestamp }}/release_notes.txt
        files: |
          data/${{ env.test_timestamp }}/morphosource_data_complete.json
          data/${{ env.test_timestamp }}/test_info.json
          data/${{ env.daily_timestamp }}/updated_morphosource_data.json

    - name: Commit data files
      if: always()
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        echo "::group::Files to be committed"
        git add -f "data/${{ env.test_timestamp }}/"
        git add -f "data/${{ env.daily_timestamp }}/"
        git status
        echo "::endgroup::"
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Test: Daily check data [${{ env.test_timestamp }}]"
          git push origin HEAD:main
        fi

    - name: Upload Test Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-daily-logs-${{ env.test_timestamp }}
        path: |
          data/${{ env.test_timestamp }}/*
          data/${{ env.daily_timestamp }}/* 