name: Test MorphoSource Screenshots Analysis
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'MorphoSource URL to process'
        required: true
        default: 'https://www.morphosource.org/concern/media/000704012'
        type: string

jobs:
  capture-screenshots:
    runs-on: ubuntu-latest
    
    env:
      PYTHONUNBUFFERED: 1
      DISPLAY: :99
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Setup virtual display
      run: |
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        sleep 2
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libopengl0 mesa-utils chromium-browser libnss3 libgbm1 libasound2
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager requests Pillow urllib3 openai
    
    - name: Create test directory
      run: mkdir -p test_screenshots
    
    - name: Create URL file
      run: |
        echo "${{ github.event.inputs.url }}" > url.txt
    
    - name: Capture screenshots
      run: |
        python .github/scripts/ct_image_to_text.py url.txt test_screenshots
      
    - name: List generated files
      if: always()
      run: |
        echo "Generated files:"
        ls -la test_screenshots/*.png || true
        ls -la error_*.txt || true
    
    - name: Upload screenshots
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: morphosource_screenshots
        path: |
          test_screenshots/*.png
          error_*.txt
        retention-days: 7

  analyze-screenshots:
    needs: capture-screenshots
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai Pillow
    
    - name: Download screenshots
      uses: actions/download-artifact@v3
      with:
        name: morphosource_screenshots
        path: analysis_input
    
    - name: Run OpenAI analysis
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python .github/scripts/generate_text_with_images.py analysis_input
    
    - name: Upload analysis results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: analysis_results
        path: |
          analysis_output.txt
          error_*.txt
        retention-days: 7
