name: "Test Workflow"

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_PAT }}

      - name: Create and commit workflow
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
        run: |
          # Create test workflow file
          mkdir -p .github/workflows
          cat > .github/workflows/hello_world.yml << 'EOL'
          name: Hello World
          on: [workflow_dispatch]
          jobs:
            hello:
              runs-on: ubuntu-latest
              steps:
                - name: Say hello
                  run: echo "Hello, World!"
          EOL
          
          # Configure git with token
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          
          # Add and commit the changes
          git add .github/workflows/hello_world.yml
          git commit -m "Add test workflow"
          git push 
