name: "Test Workflow"

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to test'
        required: true
        type: string

permissions:
  contents: write
  workflows: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set branch name
        id: set-branch
        run: |
          BRANCH_NAME="claude-pr/issue-${{ github.event.inputs.issue_number }}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "Using branch: $BRANCH_NAME"

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.set-branch.outputs.branch_name }}
          persist-credentials: true

      - name: Create and commit workflow
        env:
          WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
        run: |
          # Create test workflow file
          mkdir -p .github/workflows
          cat > .github/workflows/hello_world.yml << 'EOL'
          name: Hello World
          on: [workflow_dispatch]
          jobs:
            hello:
              runs-on: ubuntu-latest
              steps:
                - name: Say hello
                  run: echo "Hello, World!"
          EOL
          
          # Configure git with PAT for workflow push
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${WORKFLOW_PAT}@github.com/${{ github.repository }}.git
          
          # Add and commit the changes
          git add .github/workflows/hello_world.yml
          git commit -m "Add test workflow to issue #${{ github.event.inputs.issue_number }}"
          git push origin HEAD:${{ steps.set-branch.outputs.branch_name }} 
